logincount/logincount/urls.py
from django.contrib import admin
from django.urls import path
from blog import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('about/',views.about,name='about'),
    path('contact/',views.contact,name='contact'),
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('signup/',views.user_signup,name='signup'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('addpost/',views.add_post,name='addpost'),
    path('edit/<int:id>/',views.edit,name='edit'),
    path('delete/<int:id>/',views.delete,name='delete'),
]

logincount/blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title= models.CharField(max_length=150)
    desc= models.TextField()

logincount/blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,UsernameField
from django.contrib.auth.models import User
from django.utils.translation import gettext,gettext_lazy as _
from .models import Post

class SignUpFrom(UserCreationForm):
    password1 = forms.CharField(label='Password',widget=forms.PasswordInput(attrs={'class':'form-control'})) 
    password2 = forms.CharField(label='Confirm Password(again)',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    class Meta:
        model =User
        fields = ['username','first_name','last_name','email']
        labels = {'first_name':'First Name','last_name':'Last Name','email':'Email'}
        widgets = {'username':forms.TextInput(attrs={'class':'form-control'}),
                   'first_name':forms.TextInput(attrs={'class':'form-control'}),
                   'last_name':forms.TextInput(attrs={'class':'form-control'}),
                   'email':forms.EmailInput(attrs={'class':'form-control'}),
                   }


class LoginFrom(AuthenticationForm):
   username = UsernameField(widget=forms.TextInput(attrs={'autofocus':True,'class':'form-control'}))
   password = forms.CharField(label=_("Password"),strip=False,widget=forms.PasswordInput(attrs={'autocomplete':'current-password','class':'form-control'}))

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','desc']
        labels = {'title':'Title','desc':'Description'}
        widgets = {'title':forms.TextInput(attrs={'class':'form-contol'}),
        'desc':forms.Textarea(attrs={'class':'form-control'}),}

logincount/blog/views.py
from django.shortcuts import render,HttpResponseRedirect
from .forms import SignUpFrom,LoginFrom,PostForm
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from .models import Post
from django.contrib.auth.models import Group
from django.core.cache import cache

# Create your views here.

def home(request):
    posts =Post.objects.all()
    return render(request,'home.html',{'posts':posts})

def about(request):
    return render(request,'about.html')

def contact(request):
    return render(request,'contact.html')

def user_login(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            form = LoginFrom(request=request, data=request.POST)
            if form.is_valid():
                uname = form.cleaned_data['username']
                upass = form.cleaned_data['password']
                user = authenticate(username=uname, password=upass)
                if user is not None:
                    login(request,user)
                    messages.success(request,"Log in successfully")
                    return HttpResponseRedirect('/dashboard/')
        else:
            form = LoginFrom()  
        return render(request,'login.html',{'form':form})
    else:
        return HttpResponseRedirect('/dashboard/')


def user_logout(request):
    logout(request)
    messages.success(request, 'You have been logged out successfully.')
    return HttpResponseRedirect('/')

def user_signup(request):
 if request.method=="POST":
    form=SignUpFrom(request.POST)
    if form.is_valid():
      messages.success(request,"Congratulations!! You have become an Author")
      user = form.save()
      group = Group.objects.get(name='Author')
      user.groups.add(group)
 else:     
  form =SignUpFrom()
 return render(request,'signup.html',{'form':form})

def dashboard(request):
    if request.user.is_authenticated:
        posts = Post.objects.all()
        user = request.user
        full_name = user.get_full_name()
        groups = user.groups.all()
        ct = cache.get('count', version=user.pk)
        ip = request.session.get('ip',0)
        return render(request, 'dashboard.html', {'posts': posts, 'full_name': full_name, 'groups': groups,'ip':ip,'ct':ct})
    else:
        return HttpResponseRedirect('/login/')
  
def add_post(request):
   if request.user.is_authenticated:
    if request.method == "POST":
       form = PostForm(request.POST)
       if form.is_valid():
          title =form.cleaned_data['title']
          desc = form.cleaned_data['desc']
          pst = Post(title=title,desc= desc)
          pst.save()
          form = PostForm()
    else:
      form= PostForm()
    return render(request,'addpost.html',{'form':form})
   else:
      return HttpResponseRedirect('/login/')
   
def edit(request,id):
   if request.user.is_authenticated:
     if request.method == "POST":
        pi = Post.objects.get(pk=id)
        form=PostForm(request.POST,instance=pi)
        if form.is_valid():
         form.save()
        return HttpResponseRedirect('/dashboard/')
     else:
        pi=Post.objects.get(pk=id)
        form = PostForm(instance=pi)
     return render(request,'updatepost.html',{'form':form})
   else:
     return HttpResponseRedirect('/login/')
   
def delete(request,id):
    if request.user.is_authenticated:
        if request.method == "POST":
           pi = Post.objects.get(pk=id)
           pi.delete()
           return HttpResponseRedirect('/dashboard/')
    else:
        return HttpResponseRedirect('/login/')

logincount/blog/templates/about.html
{% extends "base.html" %}
{% load static %}

{% block content  %}


<div class=" about col-sm-10">
    <h3 class="text-white my-5 text-center">About Page</h3>
    <p class="text-center">A blog (a truncation of "weblog")[1] is an informational 
        website consisting of discrete, often informal diary-style text entries (posts).
         Posts are typically displayed in reverse chronological order so that the most
          recent post appears first, at the top of the web page. In the 2000s, blogs were 
          often the work of a single individual, occasionally of a small group, and often 
          covered a single subject or topic. In the 2010s, "multi-author blogs" (MABs) emerged, 
          featuring the writing of multiple authors and sometimes professionally edited. MABs from newspapers,
           other media outlets, universities, think tanks, advocacy groups, and similar institutions account for 
           an increasing quantity of blog traffic. The rise of Twitter and other "microblogging" systems helps
            integrate MABs and single-author blogs into the news media. Blog can also be used as a verb, meaning 
            to maintain or add content to a blog. </p>

</div>

{% endblock content  %} 

logincount/blog/templates/addpost.html
{% extends "base.html" %}
{% load static %}

{% block content  %}
<div class="col-sm-10">
    <h3 class="text-white my-5 ">Dashboard/Add Post</h3>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Add" class="btn btn-success">
        <a href="{% url 'dashboard' %}" class="btn btn-danger">Cancle</a>
    </form>
</div>
{% endblock content  %} 

logincount/blog/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
    <title>Document</title>
</head>
<body>
    <div class="container-fluid bg-dark">
        {% include "navbar.html" %}
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                {% block msg %}
                {% endblock msg %}
            </div>
        </div>
        <div class="row">
            {% block side %}
            
            {% endblock side %}

            {% block content %}
            {% endblock content %}

        </div>
    </div>
        
<script src="{% static 'blog/js/jquery.js' %}"></script>
<script src="{% static 'blog/js/popper.js' %}"></script>
<script src="{% static 'blog/js/bootstrap.js' %}"></script>
</body>
</html>

logincount/blog/templates/contact.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">Contact Page</h3>
    <form action="">
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="inputName">Name</label>
                <input type="text" class="form-control" id="inputName">
            </div>
            <div class="form-group col-md-6">
                <label for="inputEmail">Email</label>
                <input type="email" class="form-control" id="inputEmail">
            </div>
        </div>
        <div class="form-group">
            <label for="inputAddress">Address</label>
            <input type="text" class="form-control" id="inputAddress">
        </div>
        <div class="form-group">
            <label for="message">Message</label>
            <textarea class="form-control" id="message" rows="3"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Send</button>
    </form>
</div>
{% endblock content %}

logincount/blog/templates/dashboard.html
{% extends "base.html" %}
{% load static %}


{% block msg %}
    
    {% if messages %}
        {% for message in  messages %}
            <div {% if message.tags %} class="alert alert-{{message.tags}} alert-dismissible fade show" {% endif %}>
                <strong>{{message}}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="chose">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}
{% endblock msg %} 

{% block side %}
<div class="col-sm-2 text-white my-5 text-center">
    <h4 class="my-5">Profile</h4>
    <h5>{{full_name}}</h5>
    {% for group in groups %}
    <p>{{group.name}}</p>
    {% endfor %}
    <button type="button" class="btn btn-primary mt-3">Login Times <span class="badge badge-light">{{ct}}</span></button>
    <h5 class='mt-3'>Your IP: {{ip}}</h5>
</div>
{% endblock side %}



{% block content %}
    <div class="col-sm-10">
        <h3 class="text-white my-5">Dashboard Page</h3>
        <a href="{% url 'addpost' %}" class="btn btn-success">Add Post</a>
        <h4 class="text-center alert alert-info mt-3">Show Post Information</h4>
        {% if posts %}
            <table class="table table-hover bg-white">
                <thead>
                    <tr class="text-center">
                        <th scope="col" style="width:2%">ID</th>
                        <th scope="col" style="width:28%">Title</th>
                        <th scope="col" style="width:55%">Description</th>
                        <th scope="col" style="width:15%">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for post in posts %}
                        <tr>
                            <th scope="row">{{post.id}}</th>
                            <td>{{post.title}}</td>
                            <td>{{post.desc}}</td>
                            <td class="text-center">
                                <a href="{% url 'edit' post.id %}" class="btn btn-warning btn-sm">Edit</a>
                                {% if perms.blog.delete_post %}
                                <form action="{% url 'delete' post.id %}" method="post" class="d-inline">
                                    {% csrf_token %}
                                    <input type="submit" class="btn btn-danger btn-sm" value="Delete">
                                    {% endif %}
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <h4 class="text-center alert alert-warning">No Records</h4>
        {% endif %}
    </div>
{% endblock content %}

logincount/blog/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block content  %}
<div class="col-sm-10">
    <h3 class="text-white my-5 ">Home Page</h3>
    {% for post in posts %}
      <div class="jumbotron jumbotron-fluid jumbo-color">
          <div class="container">
            <h1 class="display-4 ">{{post.title}}</h1>
            <p class="lead">{{post.desc}}</p>
          </div>
      </div>
    {% endfor %}
</div>
{% endblock content  %} 

logincount/blog/templates/login.html
{% extends "base.html" %}
{% load static %}

{% block content  %}
<div class="col-sm-10">
    <h3 class="text-white my-5 ">Login Page</h3>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {% for fm in form %}
    <div class="form-group">
    {{fm.label_tag}} {{fm}} <small class="text-warning">{{fm.errors|striptags}}</small>
</div>
    {% endfor %}
    <br>
    <input type="submit" value="submit" class="btn btn-primary">
    {% if form.non_field_errors  %}
      {% for error in form.non_field_errors  %}
      <p class="alert alert-danger my-3">{{error}}</p>
      {% endfor %}
    {% endif %}
  </form>
</div>
{% endblock content  %} 

logincount/blog/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Mini Blog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto"> <!-- Added ms-auto class for right alignment -->
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about' %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contact' %}">Contact</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'signup' %}">Signup</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

logincount/blog/templates/signup.html
{% extends "base.html" %}
{% load static %}

{% block content  %}
<div class="col-sm-10">
    <h3 class="text-white my-5 ">Become an Author</h3>
    {% if messages %}
    {% for message in  messages %}
    <p{% if message.tags %} class="alert alert-{{message.tags}}" mb-5" {% endif %}>{{message}} </p>
    {% endfor %}
    {% endif %}
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {% for fm in form %}
    {{fm.label_tag}} {{fm}} <small class="text-warning"> {{fm.errors|striptags}}</small>
    {% endfor %}
    <br>
    <input type="submit" value="submit" class="btn btn-primary">
    {% if form.non_field_errors  %}
      {% for error in form.non_field_errors  %}
      <p class="alert alert-danger my-3">{{error}}</p>
      {% endfor %}
    {% endif %}
  </form>
</div>
{% endblock content  %} 

logincount/blog/templates/updatepost.html
{% extends "base.html" %}
{% load static %}

{% block content  %}
<div class="col-sm-10">
    <h3 class="text-white my-5 ">Dashboard/Update Post</h3>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Edit" class="btn btn-success">
        <a href="{% url 'dashboard' %}" class="btn btn-danger">Cancle</a>
    </form>
</div>
{% endblock content  %} 